id: WENGE_POOL
type: FEATURE

distributor:
  type: SAMPLER
  sampler:
    type: PROBABILITY
    sampler:
      type: OPEN_SIMPLEX_2
      frequency: 0.03
      salt: 2657
  threshold: 0.75

locator:
  type: AND
  locators:
    - type: PATTERN
      range: &range
        min: -192
        max: 320
      pattern:
        type: AND
        patterns:
          - type: MATCH_AIR
            offset: 1
          - type: MATCH_SET
            blocks:
              - kubejs:wenge
              - minecraft:basalt
              - create:scoria
              - kubejs:caverock
            offset: 0
          - type: MATCH_SOLID
            offset: -1
    - type: ADJACENT_PATTERN
      range: *range
      match-all: true
      pattern:
        type: OR
        patterns:
          - type: MATCH_SET
            blocks:
              - kubejs:wenge
              - minecraft:basalt
              - create:scoria
              - kubejs:caverock
            offset: 0
          - type: MATCH
            block: minecraft:lava
            offset: 0

structures:
  distribution:
    type: CONSTANT
  structures: BLOCK:minecraft:lava